name : precise_gps_env
dependencies :
  - python == 3.7.10
  - numpy == 1.19.5
  - tensorflow == 2.4.0
  - matplotlib == 3.2.2
  - pandas == 1.1.5
  - scikit-learn == 0.22.2.post1
  - scipy == 1.4.1
  - xlrd == 1.1.0
  - pip == 19.3.1
  - pip :
    - gpflow == 2.2.1
    - latextable == 0.1.1
    - tensorflow_probability == 0.12.1